In [1]:
# read file
import numpy as np
import pandas as pd  # for data analytics

# The two packages below are for plotting
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import MultiLabelBinarizer

/Users/mrudula/opt/anaconda3/lib/python3.9/site-packages/pandas/core/computation/expressions.py:21: UserWarning: Pandas requires version '2.8.4' or newer of 'numexpr' (version '2.8.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
/Users/mrudula/opt/anaconda3/lib/python3.9/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.2' currently installed).
  from pandas.core import (
/Users/mrudula/opt/anaconda3/lib/python3.9/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.26.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [2]:
df = pd.read_csv('cleaned_data.csv')

In [3]:
df.head()

Customer_ID     Month  Age Occupation  Annual_Income  Monthly_Inhand_Salary  \
0  CUS_0x1000   January   17     Lawyer       30625.94            2706.161667   
1  CUS_0x1000  February   17     Lawyer       30625.94            2706.161667   
2  CUS_0x1000     March   17     Lawyer       30625.94            2706.161667   
3  CUS_0x1000     April   17     Lawyer       30625.94            2706.161667   
4  CUS_0x1000       May   17     Lawyer       30625.94            2706.161667   

   Num_Bank_Accounts  Num_Credit_Card  Interest_Rate  Num_of_Loan  ...  \
0                6.0              5.0             27          2.0  ...   
1                6.0              5.0             27          2.0  ...   
2                6.0              5.0             27          2.0  ...   
3                6.0              5.0             27          2.0  ...   
4                6.0              5.0             27          2.0  ...   

  Credit_Mix  Outstanding_Debt  Credit_Utilization_Ratio  Credit_History_Age  \
0        Bad           1562.91                 26.612093           10.166667   
1        Bad           1562.91                 29.439759           10.250000   
2        Bad           1562.91                 38.285928           10.333333   
3        Bad           1562.91                 32.843081           10.416667   
4        Bad           1562.91                 32.330508           10.500000   

   Payment_of_Min_Amount Total_EMI_per_month  Amount_invested_monthly  \
0                    Yes            42.94109               244.750283   
1                    Yes            42.94109               176.132567   
2                    Yes            42.94109               109.056519   
3                    Yes            42.94109                87.909909   
4                    Yes            42.94109               191.834767   

                  Payment_Behaviour  Monthly_Balance Credit_Score  
0    Low_spent_Large_value_payments       252.924793     Standard  
1   High_spent_Small_value_payments       311.542510         Poor  
2  High_spent_Medium_value_payments       368.618557         Poor  
3  High_spent_Medium_value_payments       419.765167         Poor  
4    Low_spent_Large_value_payments       305.840309         Poor  

[5 rows x 25 columns]

In [4]:
df['Monthly_Balance'].describe()

count    100000.000000
mean        395.846943
std         218.975178
min           0.000000
25%         266.732614
50%         334.065569
75%         467.378940
max        1602.040519
Name: Monthly_Balance, dtype: float64

In [5]:
# Create a summary DataFrame with data types and unique counts
summary = pd.DataFrame({
    'Type': df.dtypes,
    'Unique Values': df.nunique()
})
print(summary, len(df.columns)) # Type_of_Loan has too many values...why?

                             Type  Unique Values
Customer_ID                object          12500
Month                      object              8
Age                         int64             43
Occupation                 object             15
Annual_Income             float64          13487
Monthly_Inhand_Salary     float64          13235
Num_Bank_Accounts         float64             12
Num_Credit_Card           float64             12
Interest_Rate               int64           1750
Num_of_Loan               float64             10
Type_of_Loan               object           6260
Delay_from_due_date       float64             68
Num_of_Delayed_Payment    float64             29
Changed_Credit_Limit      float64           3716
Num_Credit_Inquiries      float64             18
Credit_Mix                 object              3
Outstanding_Debt          float64          12203
Credit_Utilization_Ratio  float64         100000
Credit_History_Age        float64            541
Payment_of_Min_Amoun

In [6]:
# Remove all instances of "and " and also strip leading/trailing whitespaces properly
df['Type_of_Loan_Cleaned'] = df['Type_of_Loan'].str.replace(r'\band\b', '',
                                                            regex=True).str.replace(r'\s+', ' ', regex=True).str.strip()

# Now split the cleaned values
df['Type_of_Loan_Split'] = df['Type_of_Loan_Cleaned'].str.split(', ')
print(df['Type_of_Loan_Split'].head())

0    [Credit-Builder Loan, Home Equity Loan]
1    [Credit-Builder Loan, Home Equity Loan]
2    [Credit-Builder Loan, Home Equity Loan]
3    [Credit-Builder Loan, Home Equity Loan]
4    [Credit-Builder Loan, Home Equity Loan]
Name: Type_of_Loan_Split, dtype: object


In [7]:
mlb = MultiLabelBinarizer()

loan_one_hot = mlb.fit_transform(df['Type_of_Loan_Split'])
loan_one_hot_df = pd.DataFrame(loan_one_hot, columns=mlb.classes_)
print(loan_one_hot[:6])
print(loan_one_hot_df.head()) 
# check 'and Home Equity Loan' is count as 'Home Equity Loan'

[[0 1 0 1 0 0 0 0 0]
 [0 1 0 1 0 0 0 0 0]
 [0 1 0 1 0 0 0 0 0]
 [0 1 0 1 0 0 0 0 0]
 [0 1 0 1 0 0 0 0 0]
 [0 1 0 1 0 0 0 0 0]]
   Auto Loan  Credit-Builder Loan  Debt Consolidation Loan  Home Equity Loan  \
0          0                    1                        0                 1   
1          0                    1                        0                 1   
2          0                    1                        0                 1   
3          0                    1                        0                 1   
4          0                    1                        0                 1   

   Mortgage Loan  Not Specified  Payday Loan  Personal Loan  Student Loan  
0              0              0            0              0             0  
1              0              0            0              0             0  
2              0              0            0              0             0  
3              0              0            0              0             0  
4           

In [8]:
# Concatenate the one-hot encoded DataFrame with the original DataFrame
df_new_typeOfLoan = pd.concat([df, loan_one_hot_df], axis=1)

In [9]:
# Drop the unecessary col: 'Customer_ID', 'Type_of_Loan ', 
# 'Type_of_Loan_Split','Type_of_Loan_Cleaned', 'Credit_Score'
# Drop 'Annual_Income'cuz monthly salary and annual income are highly related, so only keep one

convert_df = df_new_typeOfLoan.drop(['Customer_ID', 'Annual_Income','Type_of_Loan', 
    'Type_of_Loan_Split','Type_of_Loan_Cleaned', 'Credit_Score'], axis=1) 
print(convert_df.dtypes)

Month                        object
Age                           int64
Occupation                   object
Monthly_Inhand_Salary       float64
Num_Bank_Accounts           float64
Num_Credit_Card             float64
Interest_Rate                 int64
Num_of_Loan                 float64
Delay_from_due_date         float64
Num_of_Delayed_Payment      float64
Changed_Credit_Limit        float64
Num_Credit_Inquiries        float64
Credit_Mix                   object
Outstanding_Debt            float64
Credit_Utilization_Ratio    float64
Credit_History_Age          float64
Payment_of_Min_Amount        object
Total_EMI_per_month         float64
Amount_invested_monthly     float64
Payment_Behaviour            object
Monthly_Balance             float64
Auto Loan                     int64
Credit-Builder Loan           int64
Debt Consolidation Loan       int64
Home Equity Loan              int64
Mortgage Loan                 int64
Not Specified                 int64
Payday Loan                 

In [10]:
convert_df.columns

Index(['Month', 'Age', 'Occupation', 'Monthly_Inhand_Salary',
       'Num_Bank_Accounts', 'Num_Credit_Card', 'Interest_Rate', 'Num_of_Loan',
       'Delay_from_due_date', 'Num_of_Delayed_Payment', 'Changed_Credit_Limit',
       'Num_Credit_Inquiries', 'Credit_Mix', 'Outstanding_Debt',
       'Credit_Utilization_Ratio', 'Credit_History_Age',
       'Payment_of_Min_Amount', 'Total_EMI_per_month',
       'Amount_invested_monthly', 'Payment_Behaviour', 'Monthly_Balance',
       'Auto Loan', 'Credit-Builder Loan', 'Debt Consolidation Loan',
       'Home Equity Loan', 'Mortgage Loan', 'Not Specified', 'Payday Loan',
       'Personal Loan', 'Student Loan'],
      dtype='object')

In [11]:
df_dummies = pd.get_dummies(df, columns=['Occupation','Month',
                                         'Credit_Mix','Payment_of_Min_Amount',
                                        'Payment_Behaviour'], drop_first=False)

df_dummies_final = df_dummies.drop(columns=['Customer_ID','Age',
                                    'Monthly_Inhand_Salary','Num_Bank_Accounts', 
                                    'Num_Credit_Card', 'Interest_Rate', 'Num_of_Loan',
                                    'Type_of_Loan', 'Delay_from_due_date', 'Num_of_Delayed_Payment',
                                    'Changed_Credit_Limit', 'Num_Credit_Inquiries', 'Outstanding_Debt',
                                    'Credit_Utilization_Ratio', 'Credit_History_Age', 'Total_EMI_per_month',
                                    'Amount_invested_monthly', 'Monthly_Balance'], axis=1)

In [12]:
df_dummies_final.columns

Index(['Annual_Income', 'Credit_Score', 'Type_of_Loan_Cleaned',
       'Type_of_Loan_Split', 'Occupation_Accountant', 'Occupation_Architect',
       'Occupation_Developer', 'Occupation_Doctor', 'Occupation_Engineer',
       'Occupation_Entrepreneur', 'Occupation_Journalist', 'Occupation_Lawyer',
       'Occupation_Manager', 'Occupation_Mechanic', 'Occupation_Media_Manager',
       'Occupation_Musician', 'Occupation_Scientist', 'Occupation_Teacher',
       'Occupation_Writer', 'Month_April', 'Month_August', 'Month_February',
       'Month_January', 'Month_July', 'Month_June', 'Month_March', 'Month_May',
       'Credit_Mix_Bad', 'Credit_Mix_Good', 'Credit_Mix_Standard',
       'Payment_of_Min_Amount_NM', 'Payment_of_Min_Amount_No',
       'Payment_of_Min_Amount_Yes',
       'Payment_Behaviour_High_spent_Large_value_payments',
       'Payment_Behaviour_High_spent_Medium_value_payments',
       'Payment_Behaviour_High_spent_Small_value_payments',
       'Payment_Behaviour_Low_spent_Large_v

In [13]:
df_all_dummies = pd.concat([convert_df, df_dummies_final], axis=1)
# print(df_all_dummies.head()) # 87 columns...well, reasonable
# drop the old ones
df_final = df_all_dummies.drop(columns=['Occupation','Month',
                                         'Credit_Mix','Payment_of_Min_Amount',
                                        'Payment_Behaviour'], axis=1)
print(df_final.head()) # 82 columns...correct

   Age  Monthly_Inhand_Salary  Num_Bank_Accounts  Num_Credit_Card  \
0   17            2706.161667                6.0              5.0   
1   17            2706.161667                6.0              5.0   
2   17            2706.161667                6.0              5.0   
3   17            2706.161667                6.0              5.0   
4   17            2706.161667                6.0              5.0   

   Interest_Rate  Num_of_Loan  Delay_from_due_date  Num_of_Delayed_Payment  \
0             27          2.0                 62.0                    25.0   
1             27          2.0                 62.0                    23.0   
2             27          2.0                 62.0                    28.0   
3             27          2.0                 64.0                    25.0   
4             27          2.0                 67.0                    25.0   

   Changed_Credit_Limit  Num_Credit_Inquiries  ...  Credit_Mix_Standard  \
0                  1.63                  

# Scaling Numeric Data

In [14]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 64 columns):
 #   Column                                              Non-Null Count   Dtype  
---  ------                                              --------------   -----  
 0   Age                                                 100000 non-null  int64  
 1   Monthly_Inhand_Salary                               100000 non-null  float64
 2   Num_Bank_Accounts                                   100000 non-null  float64
 3   Num_Credit_Card                                     100000 non-null  float64
 4   Interest_Rate                                       100000 non-null  int64  
 5   Num_of_Loan                                         100000 non-null  float64
 6   Delay_from_due_date                                 100000 non-null  float64
 7   Num_of_Delayed_Payment                              100000 non-null  float64
 8   Changed_Credit_Limit                                100000 non-nu

In [15]:
df_final = df_final.drop(columns=['Type_of_Loan_Cleaned','Type_of_Loan_Split'], axis=1)

In [16]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 62 columns):
 #   Column                                              Non-Null Count   Dtype  
---  ------                                              --------------   -----  
 0   Age                                                 100000 non-null  int64  
 1   Monthly_Inhand_Salary                               100000 non-null  float64
 2   Num_Bank_Accounts                                   100000 non-null  float64
 3   Num_Credit_Card                                     100000 non-null  float64
 4   Interest_Rate                                       100000 non-null  int64  
 5   Num_of_Loan                                         100000 non-null  float64
 6   Delay_from_due_date                                 100000 non-null  float64
 7   Num_of_Delayed_Payment                              100000 non-null  float64
 8   Changed_Credit_Limit                                100000 non-nu

In [17]:
df_numeric = df_final.loc[:, df_final.columns != 'Credit_Score']
df_numeric.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 61 columns):
 #   Column                                              Non-Null Count   Dtype  
---  ------                                              --------------   -----  
 0   Age                                                 100000 non-null  int64  
 1   Monthly_Inhand_Salary                               100000 non-null  float64
 2   Num_Bank_Accounts                                   100000 non-null  float64
 3   Num_Credit_Card                                     100000 non-null  float64
 4   Interest_Rate                                       100000 non-null  int64  
 5   Num_of_Loan                                         100000 non-null  float64
 6   Delay_from_due_date                                 100000 non-null  float64
 7   Num_of_Delayed_Payment                              100000 non-null  float64
 8   Changed_Credit_Limit                                100000 non-nu

In [18]:
df_numeric.columns

Index(['Age', 'Monthly_Inhand_Salary', 'Num_Bank_Accounts', 'Num_Credit_Card',
       'Interest_Rate', 'Num_of_Loan', 'Delay_from_due_date',
       'Num_of_Delayed_Payment', 'Changed_Credit_Limit',
       'Num_Credit_Inquiries', 'Outstanding_Debt', 'Credit_Utilization_Ratio',
       'Credit_History_Age', 'Total_EMI_per_month', 'Amount_invested_monthly',
       'Monthly_Balance', 'Auto Loan', 'Credit-Builder Loan',
       'Debt Consolidation Loan', 'Home Equity Loan', 'Mortgage Loan',
       'Not Specified', 'Payday Loan', 'Personal Loan', 'Student Loan',
       'Annual_Income', 'Occupation_Accountant', 'Occupation_Architect',
       'Occupation_Developer', 'Occupation_Doctor', 'Occupation_Engineer',
       'Occupation_Entrepreneur', 'Occupation_Journalist', 'Occupation_Lawyer',
       'Occupation_Manager', 'Occupation_Mechanic', 'Occupation_Media_Manager',
       'Occupation_Musician', 'Occupation_Scientist', 'Occupation_Teacher',
       'Occupation_Writer', 'Month_April', 'Month_Augus

In [19]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
 
df_numeric[df_numeric.columns] = scaler.fit_transform(df_numeric)

/var/folders/8w/f1nm4bk161nf0bdc91693vr40000gn/T/ipykernel_3460/2734800432.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_numeric[df_numeric.columns] = scaler.fit_transform(df_numeric)


In [20]:
df_numeric.head()

Age  Monthly_Inhand_Salary  Num_Bank_Accounts  Num_Credit_Card  \
0  0.071429               0.161232           0.545455         0.454545   
1  0.071429               0.161232           0.545455         0.454545   
2  0.071429               0.161232           0.545455         0.454545   
3  0.071429               0.161232           0.545455         0.454545   
4  0.071429               0.161232           0.545455         0.454545   

   Interest_Rate  Num_of_Loan  Delay_from_due_date  Num_of_Delayed_Payment  \
0       0.004486     0.222222             0.925373                0.892857   
1       0.004486     0.222222             0.925373                0.821429   
2       0.004486     0.222222             0.925373                1.000000   
3       0.004486     0.222222             0.955224                0.892857   
4       0.004486     0.222222             1.000000                0.892857   

   Changed_Credit_Limit  Num_Credit_Inquiries  ...  Credit_Mix_Standard  \
0              0.044090              0.588235  ...                  0.0   
1              0.044090              0.647059  ...                  0.0   
2              0.044090              0.647059  ...                  0.0   
3              0.044090              0.647059  ...                  0.0   
4              0.071139              0.647059  ...                  0.0   

   Payment_of_Min_Amount_NM  Payment_of_Min_Amount_No  \
0                       0.0                       0.0   
1                       0.0                       0.0   
2                       0.0                       0.0   
3                       0.0                       0.0   
4                       0.0                       0.0   

   Payment_of_Min_Amount_Yes  \
0                        1.0   
1                        1.0   
2                        1.0   
3                        1.0   
4                        1.0   

   Payment_Behaviour_High_spent_Large_value_payments  \
0                                                0.0   
1                                                0.0   
2                                                0.0   
3                                                0.0   
4                                                0.0   

   Payment_Behaviour_High_spent_Medium_value_payments  \
0                                                0.0    
1                                                0.0    
2                                                1.0    
3                                                1.0    
4                                                0.0    

   Payment_Behaviour_High_spent_Small_value_payments  \
0                                                0.0   
1                                                1.0   
2                                                0.0   
3                                                0.0   
4                                                0.0   

   Payment_Behaviour_Low_spent_Large_value_payments  \
0                                               1.0   
1                                               0.0   
2                                               0.0   
3                                               0.0   
4                                               1.0   

   Payment_Behaviour_Low_spent_Medium_value_payments  \
0                                                0.0   
1                                                0.0   
2                                                0.0   
3                                                0.0   
4                                                0.0   

   Payment_Behaviour_Low_spent_Small_value_payments  
0                                               0.0  
1                                               0.0  
2                                               0.0  
3                                               0.0  
4                                               0.0  

[5 rows x 61 columns]

In [21]:
df_numeric.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 61 columns):
 #   Column                                              Non-Null Count   Dtype  
---  ------                                              --------------   -----  
 0   Age                                                 100000 non-null  float64
 1   Monthly_Inhand_Salary                               100000 non-null  float64
 2   Num_Bank_Accounts                                   100000 non-null  float64
 3   Num_Credit_Card                                     100000 non-null  float64
 4   Interest_Rate                                       100000 non-null  float64
 5   Num_of_Loan                                         100000 non-null  float64
 6   Delay_from_due_date                                 100000 non-null  float64
 7   Num_of_Delayed_Payment                              100000 non-null  float64
 8   Changed_Credit_Limit                                100000 non-nu

In [22]:
data = pd.concat([df_numeric, df_final['Credit_Score']], axis=1)

In [23]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 62 columns):
 #   Column                                              Non-Null Count   Dtype  
---  ------                                              --------------   -----  
 0   Age                                                 100000 non-null  float64
 1   Monthly_Inhand_Salary                               100000 non-null  float64
 2   Num_Bank_Accounts                                   100000 non-null  float64
 3   Num_Credit_Card                                     100000 non-null  float64
 4   Interest_Rate                                       100000 non-null  float64
 5   Num_of_Loan                                         100000 non-null  float64
 6   Delay_from_due_date                                 100000 non-null  float64
 7   Num_of_Delayed_Payment                              100000 non-null  float64
 8   Changed_Credit_Limit                                100000 non-nu

In [24]:
data.columns

Index(['Age', 'Monthly_Inhand_Salary', 'Num_Bank_Accounts', 'Num_Credit_Card',
       'Interest_Rate', 'Num_of_Loan', 'Delay_from_due_date',
       'Num_of_Delayed_Payment', 'Changed_Credit_Limit',
       'Num_Credit_Inquiries', 'Outstanding_Debt', 'Credit_Utilization_Ratio',
       'Credit_History_Age', 'Total_EMI_per_month', 'Amount_invested_monthly',
       'Monthly_Balance', 'Auto Loan', 'Credit-Builder Loan',
       'Debt Consolidation Loan', 'Home Equity Loan', 'Mortgage Loan',
       'Not Specified', 'Payday Loan', 'Personal Loan', 'Student Loan',
       'Annual_Income', 'Occupation_Accountant', 'Occupation_Architect',
       'Occupation_Developer', 'Occupation_Doctor', 'Occupation_Engineer',
       'Occupation_Entrepreneur', 'Occupation_Journalist', 'Occupation_Lawyer',
       'Occupation_Manager', 'Occupation_Mechanic', 'Occupation_Media_Manager',
       'Occupation_Musician', 'Occupation_Scientist', 'Occupation_Teacher',
       'Occupation_Writer', 'Month_April', 'Month_Augus

# Linear SVM Model

In [26]:
var = ['Age', 'Monthly_Inhand_Salary', 'Num_Bank_Accounts', 'Num_Credit_Card',
       'Interest_Rate', 'Num_of_Loan', 'Delay_from_due_date',
       'Num_of_Delayed_Payment', 'Changed_Credit_Limit',
       'Num_Credit_Inquiries', 'Outstanding_Debt', 'Credit_Utilization_Ratio',
       'Credit_History_Age', 'Total_EMI_per_month', 'Amount_invested_monthly',
       'Monthly_Balance', 'Auto Loan', 'Credit-Builder Loan',
       'Debt Consolidation Loan', 'Home Equity Loan', 'Mortgage Loan',
       'Not Specified', 'Payday Loan', 'Personal Loan', 'Student Loan',
       'Annual_Income', 'Occupation_Accountant', 'Occupation_Architect',
       'Occupation_Developer', 'Occupation_Doctor', 'Occupation_Engineer',
       'Occupation_Entrepreneur', 'Occupation_Journalist', 'Occupation_Lawyer',
       'Occupation_Manager', 'Occupation_Mechanic', 'Occupation_Media_Manager',
       'Occupation_Musician', 'Occupation_Scientist', 'Occupation_Teacher',
       'Occupation_Writer', 'Month_April', 'Month_August', 'Month_February',
       'Month_January', 'Month_July', 'Month_June', 'Month_March', 'Month_May',
       'Credit_Mix_Bad', 'Credit_Mix_Good', 'Credit_Mix_Standard',
       'Payment_of_Min_Amount_NM', 'Payment_of_Min_Amount_No',
       'Payment_of_Min_Amount_Yes',
       'Payment_Behaviour_High_spent_Large_value_payments',
       'Payment_Behaviour_High_spent_Medium_value_payments',
       'Payment_Behaviour_High_spent_Small_value_payments',
       'Payment_Behaviour_Low_spent_Large_value_payments',
       'Payment_Behaviour_Low_spent_Medium_value_payments',
       'Payment_Behaviour_Low_spent_Small_value_payments']

credit_X = data[var]
credit_y = data['Credit_Score']
print(credit_X.shape)
print(credit_y.shape)

(100000, 61)
(100000,)


In [27]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(credit_X, credit_y, random_state = 42)

In [28]:
# Linear SVC 
from sklearn.svm import LinearSVC
from sklearn.model_selection import GridSearchCV

linear_svc = LinearSVC(random_state = 22) # must specify random state here

# Define a list of hyperparameters
params_svc = {'C':  [0.0001, 0.001, 0.01, 0.1, 1, 10, 100, 1000, 10000, 100000]}

grid_linear_svc = GridSearchCV(linear_svc, params_svc, cv = 5, n_jobs=2)
grid_linear_svc.fit(X_train, y_train)

/Users/mrudula/opt/anaconda3/lib/python3.9/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.26.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
/Users/mrudula/opt/anaconda3/lib/python3.9/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.26.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
/Users/mrudula/opt/anaconda3/lib/python3.9/site-packages/pandas/core/computation/expressions.py:21: UserWarning: Pandas requires version '2.8.4' or newer of 'numexpr' (version '2.8.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
/Users/mrudula/opt/anaconda3/lib/python3.9/site-packages/pandas/core/computation/expressions.py:21: UserWarning: Pandas requires version '2.8.4' or newer of 'numexpr' (version '2.8.1' currently inst

GridSearchCV(cv=5, estimator=LinearSVC(random_state=22), n_jobs=2,
             param_grid={'C': [0.0001, 0.001, 0.01, 0.1, 1, 10, 100, 1000,
                               10000, 100000]})

In [29]:
print(grid_linear_svc.best_params_)
print(grid_linear_svc.best_score_)
print(grid_linear_svc.score(X_test, y_test))
print(grid_linear_svc.score(X_train, y_train))

{'C': 1}
0.6478533333333334
0.64796
0.6483066666666667
